### PR TITLE
Supress useNativeDriver warning

### PR DESCRIPTION
**Pull request by HarshBhatia**
https://reactnative.dev/blog/2017/02/14/using-native-driver-for-animated#how-do-i-use-this-in-my-app

### CODE REVIEW

**Comment by SaveYourTime** [comment]
@oblador It would be helpful if this request being merged as soon as possible.

**Comment by SaveYourTime** [comment]
@HarshBhatia I think we should set `useNativeDriver` to the default value `false` instead of `true` here. (When it set to `true`, it will cause the error.)

By the way, there might be other three `Animated.spring` function needs to be set `useNativeDriver`.

**Comment by HarshBhatia** [comment]
Ok, let me do that.

**Comment by Michaelvons** [comment]
> @HarshBhatia I think we should set `useNativeDriver` to the default value `false` instead of `true` here. (When it set to `true`, it will cause the error.)
> 
> By the way, there might be other three `Animated.spring` function needs to be set `useNativeDriver`.

Works like charm !!!

**Pull request closed without merging**
