### PR TITLE
Added android back button support.

### PR DESCRIPTION
**Pull request by peterwilli**
Open a image in the overlay and use the back button to close it again :)
Still needs testing to see if the module still works on iOS :)

### CODE REVIEW

**Comment by oblador** [comment]
Thanks for your PR! I'm in the [process of rewriting this module](https://github.com/oblador/react-native-lightbox/issues/8#issuecomment-160352712) to be more versatile and tightly integrated with `Navigator` which I believe will get this feature for free. It's something I definitely want to support (I'm just iOS biased, since I don't have an android device), but I'm a bit reluctant to merge just now until the rewrite is done.

**Comment by peterwilli** [comment]
Hi @oblador, I get that :) Until then, I'll use this for myself :)
Good luck!

**Comment by dukex** [comment]
+1 for back button support

**Comment by waleedarshad-vf** [comment]
+1

**Comment by oblador** [comment]
Should be fixed by https://github.com/oblador/react-native-lightbox/pull/62

**Pull request closed without merging**
