### PR TITLE
Add didOpen/willClose

### PR DESCRIPTION
**Pull request by elliottkember**
In my app I wanted to remove some UI before the lightbox was closed, but onClose fires after the animation is done. So I added a couple of hooks for `didOpen` and `willClose`.

Ideally I'd rather have all the callbacks named consistently - willOpen / onOpen, willClose / onClose - but they're currently named inconsistently - onOpen fires before the event and onClose fires afterwards.

### CODE REVIEW

**Comment by oblador** [comment]
Thanks!

**Comment by vdikun** [comment]
I needed this feature today and was happy to see that it was available! Thank you!

**Comment by DavitVosk** [comment]
@oblador did you merge this code in? I am on the final version of this package, but it seems that the code is missing there...

**Comment by hvaoc** [comment]
@DavitVosk - For now I am using version directly from github like this.

```json
    // package.json
    "react-native-lightbox": "git://github.com/oblador/react-native-lightbox.git#0a37652"
```

**Pull request merged**
