### PR TITLE
Several changes

### PR DESCRIPTION
**Pull request by ricardovcorrea**
- New React Native 0.62.2 example
- Updated LightBox e LightBoxOverlay to functional components and hooks
- Changed TouchableHighlight to TouchableOpacity
- Fix jumping closing animation on Android
- Giving the X close button more space from the borders
- Fixed useNativeDriver is now required warning
- Added useNativeDriver true where it is possible

### CODE REVIEW

**Comment by phatlaunchdeck** [comment]
Wow this is all really impressive, but the author doesn't seem to be responsive anymore. Can you fork this out @ricardovcorrea?

**Comment by ThukuWakogi** [comment]
There is a [fork](https://github.com/cbbfcd/react-native-lightbox).

**Comment by ricardovcorrea** [comment]
@phatlaunchdeck i was not hoping giving suport to this pkg, use the form that @ThukuWakogi suggested! 

:D

**Comment by phatlaunchdeck** [comment]
Thanks @ricardovcorrea and @ThukuWakogi !

**Pull request closed without merging**
